// Auto-generated by scripts/fetchStations.ts — do not edit manually
import type { Station } from "../types";

export const STATIONS: Station[] = [
  {
    "id": "355173041",
    "name": "Daehwa",
    "nameKo": "대화",
    "lat": 37.6761485,
    "lng": 126.7474578,
    "lines": [
      "3"
    ]
  },
  {
    "id": "355173042",
    "name": "Juyeop",
    "nameKo": "주엽",
    "lat": 37.670111,
    "lng": 126.7612341,
    "lines": [
      "3"
    ]
  },
  {
    "id": "355173038",
    "name": "Jeongbalsan",
    "nameKo": "정발산",
    "lat": 37.6597112,
    "lng": 126.7732179,
    "lines": [
      "3"
    ]
  },
  {
    "id": "355173039",
    "name": "Madu",
    "nameKo": "마두",
    "lat": 37.6520005,
    "lng": 126.7777178,
    "lines": [
      "3"
    ]
  },
  {
    "id": "355173034",
    "name": "Baekseok",
    "nameKo": "백석",
    "lat": 37.6430565,
    "lng": 126.7879533,
    "lines": [
      "3"
    ]
  },
  {
    "id": "2090733291",
    "name": "Daegok",
    "nameKo": "대곡",
    "lat": 37.6318362,
    "lng": 126.8096784,
    "lines": [
      "3",
      "gyeongui"
    ]
  },
  {
    "id": "5991943795",
    "name": "Hwajeong",
    "nameKo": "화정",
    "lat": 37.6345957,
    "lng": 126.8326234,
    "lines": [
      "3"
    ]
  },
  {
    "id": "5991943823",
    "name": "Wondang",
    "nameKo": "원당",
    "lat": 37.6538264,
    "lng": 126.8433973,
    "lines": [
      "3"
    ]
  },
  {
    "id": "5991943866",
    "name": "Wonheung",
    "nameKo": "원흥",
    "lat": 37.6504946,
    "lng": 126.8737376,
    "lines": [
      "3"
    ]
  },
  {
    "id": "355173031",
    "name": "Samsong",
    "nameKo": "삼송",
    "lat": 37.6531033,
    "lng": 126.8954689,
    "lines": [
      "3"
    ]
  },
  {
    "id": "355173030",
    "name": "Jichuk",
    "nameKo": "지축",
    "lat": 37.6479341,
    "lng": 126.9149061,
    "lines": [
      "3"
    ]
  },
  {
    "id": "5281680295",
    "name": "Gupabal",
    "nameKo": "구파발",
    "lat": 37.6368537,
    "lng": 126.9187721,
    "lines": [
      "3"
    ]
  },
  {
    "id": "6033544483",
    "name": "Yeonsinnae",
    "nameKo": "연신내",
    "lat": 37.6194491,
    "lng": 126.920858,
    "lines": [
      "3",
      "6",
      "gyeongui"
    ]
  },
  {
    "id": "5930698992",
    "name": "Bulgwang",
    "nameKo": "불광",
    "lat": 37.6098806,
    "lng": 126.930398,
    "lines": [
      "3",
      "6"
    ]
  },
  {
    "id": "355173021",
    "name": "Nokbeon",
    "nameKo": "녹번",
    "lat": 37.600943,
    "lng": 126.9357156,
    "lines": [
      "3"
    ]
  },
  {
    "id": "355173018",
    "name": "Hongje (Seoul Culture Arts Univ.)",
    "nameKo": "홍제",
    "lat": 37.588674,
    "lng": 126.944199,
    "lines": [
      "3"
    ]
  },
  {
    "id": "355173026",
    "name": "Muakjae",
    "nameKo": "무악재",
    "lat": 37.5823147,
    "lng": 126.9503083,
    "lines": [
      "3"
    ]
  },
  {
    "id": "5930698988",
    "name": "Dongnimmun",
    "nameKo": "독립문",
    "lat": 37.574513,
    "lng": 126.9578197,
    "lines": [
      "3"
    ]
  },
  {
    "id": "355173059",
    "name": "Gyeongbokgung (Government Complex Seoul)",
    "nameKo": "경복궁",
    "lat": 37.5757585,
    "lng": 126.9735668,
    "lines": [
      "3"
    ]
  },
  {
    "id": "414685965",
    "name": "Anguk",
    "nameKo": "안국",
    "lat": 37.5768286,
    "lng": 126.9862272,
    "lines": [
      "3"
    ]
  },
  {
    "id": "3833429767",
    "name": "Jongno 3(sam)-ga",
    "nameKo": "종로3가",
    "lat": 37.5720185,
    "lng": 126.9916922,
    "lines": [
      "1",
      "3",
      "5"
    ]
  },
  {
    "id": "5930698986",
    "name": "Euljiro 3(sam)-ga",
    "nameKo": "을지로3가",
    "lat": 37.5663629,
    "lng": 126.9925882,
    "lines": [
      "2",
      "3"
    ]
  },
  {
    "id": "3833429777",
    "name": "Chungmuro",
    "nameKo": "충무로",
    "lat": 37.5606488,
    "lng": 126.9948063,
    "lines": [
      "3",
      "4"
    ]
  },
  {
    "id": "355173044",
    "name": "Dongguk Univ.",
    "nameKo": "동대입구",
    "lat": 37.5590197,
    "lng": 127.0057659,
    "lines": [
      "3"
    ]
  },
  {
    "id": "5933896999",
    "name": "Yaksu",
    "nameKo": "약수",
    "lat": 37.5548296,
    "lng": 127.0105499,
    "lines": [
      "3",
      "6"
    ]
  },
  {
    "id": "355173067",
    "name": "Geumho",
    "nameKo": "금호",
    "lat": 37.5480153,
    "lng": 127.0158595,
    "lines": [
      "3"
    ]
  },
  {
    "id": "660843668",
    "name": "Oksu",
    "nameKo": "옥수",
    "lat": 37.5408763,
    "lng": 127.0178475,
    "lines": [
      "3",
      "gyeongui"
    ]
  },
  {
    "id": "2028067305",
    "name": "Apgujeong",
    "nameKo": "압구정",
    "lat": 37.5261356,
    "lng": 127.0284705,
    "lines": [
      "3"
    ]
  },
  {
    "id": "2244637619",
    "name": "Sinsa",
    "nameKo": "신사",
    "lat": 37.5161705,
    "lng": 127.0196309,
    "lines": [
      "3",
      "shinbundang"
    ]
  },
  {
    "id": "6033544393",
    "name": "Jamwon",
    "nameKo": "잠원",
    "lat": 37.5127485,
    "lng": 127.0110886,
    "lines": [
      "3"
    ]
  },
  {
    "id": "3824606377",
    "name": "Express Bus Terminal",
    "nameKo": "고속터미널",
    "lat": 37.5050376,
    "lng": 127.0049022,
    "lines": [
      "3",
      "7",
      "9"
    ]
  },
  {
    "id": "5933947005",
    "name": "Seoul Nat'l Univ. of Education (Court & Public Prosecutors' Office)",
    "nameKo": "교대",
    "lat": 37.4928812,
    "lng": 127.0138064,
    "lines": [
      "2",
      "3"
    ]
  },
  {
    "id": "1939100051",
    "name": "Nambu Bus Terminal (Seoul Arts Center)",
    "nameKo": "남부터미널",
    "lat": 37.4849718,
    "lng": 127.0162904,
    "lines": [
      "3"
    ]
  },
  {
    "id": "5225259404",
    "name": "Yangjae",
    "nameKo": "양재",
    "lat": 37.4845433,
    "lng": 127.034317,
    "lines": [
      "3",
      "shinbundang"
    ]
  },
  {
    "id": "2346858827",
    "name": "Maebong",
    "nameKo": "매봉",
    "lat": 37.4870435,
    "lng": 127.0469913,
    "lines": [
      "3"
    ]
  },
  {
    "id": "5225311375",
    "name": "Dogok",
    "nameKo": "도곡",
    "lat": 37.4908838,
    "lng": 127.0554872,
    "lines": [
      "3",
      "bundang"
    ]
  },
  {
    "id": "355173102",
    "name": "Daechi",
    "nameKo": "대치",
    "lat": 37.4944502,
    "lng": 127.0632186,
    "lines": [
      "3"
    ]
  },
  {
    "id": "355173100",
    "name": "Hangnyeoul",
    "nameKo": "학여울",
    "lat": 37.4964802,
    "lng": 127.0699125,
    "lines": [
      "3"
    ]
  },
  {
    "id": "2102704507",
    "name": "Daecheong",
    "nameKo": "대청",
    "lat": 37.493654,
    "lng": 127.0795056,
    "lines": [
      "3"
    ]
  },
  {
    "id": "414684303",
    "name": "Irwon",
    "nameKo": "일원",
    "lat": 37.4837678,
    "lng": 127.0841812,
    "lines": [
      "3"
    ]
  },
  {
    "id": "5909995037",
    "name": "Suseo",
    "nameKo": "수서",
    "lat": 37.487427,
    "lng": 127.1019706,
    "lines": [
      "3",
      "bundang"
    ]
  },
  {
    "id": "5930287078",
    "name": "Garak Market",
    "nameKo": "가락시장",
    "lat": 37.4922475,
    "lng": 127.1177039,
    "lines": [
      "3",
      "8"
    ]
  },
  {
    "id": "3418807256",
    "name": "Nat'l Police Hospital",
    "nameKo": "경찰병원",
    "lat": 37.4953088,
    "lng": 127.1238319,
    "lines": [
      "3"
    ]
  },
  {
    "id": "5934012012",
    "name": "Ogeum",
    "nameKo": "오금",
    "lat": 37.5021419,
    "lng": 127.1283544,
    "lines": [
      "3",
      "5"
    ]
  },
  {
    "id": "1797562528",
    "name": "City Hall",
    "nameKo": "시청",
    "lat": 37.5630913,
    "lng": 126.9739637,
    "lines": [
      "1",
      "2"
    ]
  },
  {
    "id": "5826564342",
    "name": "Chungjeongno(Kyonggi University)",
    "nameKo": "충정로",
    "lat": 37.5593594,
    "lng": 126.9636659,
    "lines": [
      "2",
      "5"
    ]
  },
  {
    "id": "355172855",
    "name": "Ahyeon",
    "nameKo": "아현",
    "lat": 37.5574487,
    "lng": 126.9561344,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5937884697",
    "name": "Ewha Womans University",
    "nameKo": "이대",
    "lat": 37.5567916,
    "lng": 126.9458415,
    "lines": [
      "2"
    ]
  },
  {
    "id": "1918413725",
    "name": "Sinchon",
    "nameKo": "신촌",
    "lat": 37.5551787,
    "lng": 126.9369091,
    "lines": [
      "2",
      "gyeongui"
    ]
  },
  {
    "id": "5919544686",
    "name": "Hongik University",
    "nameKo": "홍대입구",
    "lat": 37.5566763,
    "lng": 126.9234645,
    "lines": [
      "2",
      "gyeongui"
    ]
  },
  {
    "id": "5916874392",
    "name": "Hapjeong",
    "nameKo": "합정",
    "lat": 37.5500781,
    "lng": 126.9146378,
    "lines": [
      "2",
      "6"
    ]
  },
  {
    "id": "6033312682",
    "name": "Dangsan",
    "nameKo": "당산",
    "lat": 37.534127,
    "lng": 126.9020714,
    "lines": [
      "2",
      "9"
    ]
  },
  {
    "id": "6033314402",
    "name": "Yeongdeungpo-gu Office",
    "nameKo": "영등포구청",
    "lat": 37.5253151,
    "lng": 126.8965366,
    "lines": [
      "2",
      "5"
    ]
  },
  {
    "id": "6033314413",
    "name": "Mullae",
    "nameKo": "문래",
    "lat": 37.518408,
    "lng": 126.8948387,
    "lines": [
      "2"
    ]
  },
  {
    "id": "660878435",
    "name": "Sindorim",
    "nameKo": "신도림",
    "lat": 37.5089506,
    "lng": 126.8911913,
    "lines": [
      "1",
      "2"
    ]
  },
  {
    "id": "5907762741",
    "name": "Daerim(Guro-gu Office)",
    "nameKo": "대림",
    "lat": 37.4932804,
    "lng": 126.8949584,
    "lines": [
      "2",
      "7"
    ]
  },
  {
    "id": "6033314427",
    "name": "Guro Digital Complex",
    "nameKo": "구로디지털단지",
    "lat": 37.4850332,
    "lng": 126.9025904,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033314468",
    "name": "Sindaebang",
    "nameKo": "신대방",
    "lat": 37.4875967,
    "lng": 126.91343,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033314482",
    "name": "Sillim",
    "nameKo": "신림",
    "lat": 37.4842228,
    "lng": 126.9296985,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033314702",
    "name": "Bongcheon",
    "nameKo": "봉천",
    "lat": 37.4823536,
    "lng": 126.9419846,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033314712",
    "name": "Seoul Nat'l University (Gwanak-gu Office)",
    "nameKo": "서울대입구",
    "lat": 37.4811907,
    "lng": 126.9527472,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033314725",
    "name": "Nakseongdae",
    "nameKo": "낙성대",
    "lat": 37.4770291,
    "lng": 126.9635445,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033314757",
    "name": "Sadang",
    "nameKo": "사당",
    "lat": 37.4764777,
    "lng": 126.9825455,
    "lines": [
      "2",
      "4"
    ]
  },
  {
    "id": "6033314783",
    "name": "Bangbae",
    "nameKo": "방배",
    "lat": 37.4814426,
    "lng": 126.9976822,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033314994",
    "name": "Seocho",
    "nameKo": "서초",
    "lat": 37.491807,
    "lng": 127.0076422,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5907762740",
    "name": "Gangnam",
    "nameKo": "강남",
    "lat": 37.4979002,
    "lng": 127.0276077,
    "lines": [
      "2",
      "shinbundang"
    ]
  },
  {
    "id": "5812010548",
    "name": "Yeoksam",
    "nameKo": "역삼",
    "lat": 37.5007895,
    "lng": 127.0369159,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5924284356",
    "name": "Seolleung",
    "nameKo": "선릉",
    "lat": 37.5044396,
    "lng": 127.0489087,
    "lines": [
      "2",
      "bundang"
    ]
  },
  {
    "id": "287525731",
    "name": "Samseong(World Trade Center Seoul)",
    "nameKo": "삼성",
    "lat": 37.5091066,
    "lng": 127.0642476,
    "lines": [
      "2"
    ]
  },
  {
    "id": "355172911",
    "name": "Sports Complex",
    "nameKo": "종합운동장",
    "lat": 37.5112839,
    "lng": 127.0753203,
    "lines": [
      "2",
      "9"
    ]
  },
  {
    "id": "6033315012",
    "name": "Jamsilsaenae",
    "nameKo": "잠실새내",
    "lat": 37.5115479,
    "lng": 127.0864332,
    "lines": [
      "2"
    ]
  },
  {
    "id": "8337914284",
    "name": "Jamsil(Songpa-gu Office)",
    "nameKo": "잠실",
    "lat": 37.5136906,
    "lng": 127.1016671,
    "lines": [
      "2",
      "8"
    ]
  },
  {
    "id": "5933687061",
    "name": "Jamsillaru",
    "nameKo": "잠실나루",
    "lat": 37.5198837,
    "lng": 127.1043045,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5933687058",
    "name": "Gangbyeon(Dongseoul Bus Terminal)",
    "nameKo": "강변",
    "lat": 37.5343289,
    "lng": 127.0952593,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5933687294",
    "name": "Guui(Gwangjin-gu Office)",
    "nameKo": "구의",
    "lat": 37.5368976,
    "lng": 127.085103,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5801559318",
    "name": "Konkuk University",
    "nameKo": "건대입구",
    "lat": 37.5407875,
    "lng": 127.0681712,
    "lines": [
      "2",
      "7"
    ]
  },
  {
    "id": "5935554452",
    "name": "Seongsu",
    "nameKo": "성수",
    "lat": 37.5448976,
    "lng": 127.0550553,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5935554449",
    "name": "Ttukseom",
    "nameKo": "뚝섬",
    "lat": 37.5475873,
    "lng": 127.0463967,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5935554434",
    "name": "Hanyang University",
    "nameKo": "한양대",
    "lat": 37.5557274,
    "lng": 127.0436837,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5801559319",
    "name": "Wangsimni(Seongdong-Gu Office)",
    "nameKo": "왕십리",
    "lat": 37.5612222,
    "lng": 127.0371358,
    "lines": [
      "2",
      "5",
      "bundang",
      "gyeongui"
    ]
  },
  {
    "id": "355172983",
    "name": "Sangwangsimni",
    "nameKo": "상왕십리",
    "lat": 37.5644254,
    "lng": 127.029212,
    "lines": [
      "2"
    ]
  },
  {
    "id": "1797587546",
    "name": "Sindang",
    "nameKo": "신당",
    "lat": 37.5656525,
    "lng": 127.0198141,
    "lines": [
      "2",
      "6"
    ]
  },
  {
    "id": "5935738070",
    "name": "Dongdaemun History & Culture Park Station (DDP)",
    "nameKo": "동대문역사문화공원",
    "lat": 37.5659047,
    "lng": 127.0081762,
    "lines": [
      "2",
      "4",
      "5"
    ]
  },
  {
    "id": "5349724970",
    "name": "Euljiro 4(sa)-ga",
    "nameKo": "을지로4가",
    "lat": 37.5666655,
    "lng": 126.9979998,
    "lines": [
      "2",
      "5"
    ]
  },
  {
    "id": "355172962",
    "name": "Euljiro 1(il)-ga (Industrial Bank of Korea)",
    "nameKo": "을지로입구",
    "lat": 37.5659777,
    "lng": 126.982607,
    "lines": [
      "2"
    ]
  },
  {
    "id": "355173346",
    "name": "Buramsan",
    "nameKo": "불암산",
    "lat": 37.6695753,
    "lng": 127.0784401,
    "lines": [
      "4"
    ]
  },
  {
    "id": "355173339",
    "name": "Sanggye",
    "nameKo": "상계",
    "lat": 37.6599912,
    "lng": 127.0726737,
    "lines": [
      "4"
    ]
  },
  {
    "id": "5914759508",
    "name": "Nowon",
    "nameKo": "노원",
    "lat": 37.6561244,
    "lng": 127.0623632,
    "lines": [
      "4",
      "7"
    ]
  },
  {
    "id": "5812233466",
    "name": "Chang-dong",
    "nameKo": "창동",
    "lat": 37.6529636,
    "lng": 127.0466586,
    "lines": [
      "1",
      "4"
    ]
  },
  {
    "id": "355173148",
    "name": "Ssangmun",
    "nameKo": "쌍문",
    "lat": 37.6484204,
    "lng": 127.0345485,
    "lines": [
      "4"
    ]
  },
  {
    "id": "355173138",
    "name": "Suyu (Gangbuk-gu Office)",
    "nameKo": "수유",
    "lat": 37.6379893,
    "lng": 127.0256914,
    "lines": [
      "4"
    ]
  },
  {
    "id": "7106108484",
    "name": "Mia",
    "nameKo": "미아",
    "lat": 37.6254296,
    "lng": 127.0264909,
    "lines": [
      "4"
    ]
  },
  {
    "id": "3835922764",
    "name": "Miasageori",
    "nameKo": "미아사거리",
    "lat": 37.6131644,
    "lng": 127.0300744,
    "lines": [
      "4"
    ]
  },
  {
    "id": "353186868",
    "name": "Gireum",
    "nameKo": "길음",
    "lat": 37.6024214,
    "lng": 127.024414,
    "lines": [
      "4"
    ]
  },
  {
    "id": "287321417",
    "name": "Sungshin Women's University",
    "nameKo": "성신여대입구",
    "lat": 37.592665,
    "lng": 127.0164111,
    "lines": [
      "4"
    ]
  },
  {
    "id": "5914829686",
    "name": "Hansung Univ. (Samseongyo)",
    "nameKo": "한성대입구",
    "lat": 37.588201,
    "lng": 127.0053156,
    "lines": [
      "4"
    ]
  },
  {
    "id": "355173201",
    "name": "Hyehwa",
    "nameKo": "혜화",
    "lat": 37.5821434,
    "lng": 127.0019312,
    "lines": [
      "4"
    ]
  },
  {
    "id": "3833429765",
    "name": "Dongdaemun",
    "nameKo": "동대문",
    "lat": 37.5707564,
    "lng": 127.0093746,
    "lines": [
      "1",
      "4"
    ]
  },
  {
    "id": "355173195",
    "name": "Myeong-dong",
    "nameKo": "명동",
    "lat": 37.5609174,
    "lng": 126.9862899,
    "lines": [
      "4"
    ]
  },
  {
    "id": "3832931179",
    "name": "Hoehyeon (Namdaemun Market)",
    "nameKo": "회현",
    "lat": 37.5587614,
    "lng": 126.978436,
    "lines": [
      "4"
    ]
  },
  {
    "id": "7366159452",
    "name": "Seoul Station",
    "nameKo": "서울역",
    "lat": 37.552576,
    "lng": 126.9724492,
    "lines": [
      "1",
      "4",
      "airport",
      "gyeongui"
    ]
  },
  {
    "id": "3818491433",
    "name": "Sookmyung Women's Univ.",
    "nameKo": "숙대입구",
    "lat": 37.5451375,
    "lng": 126.9719211,
    "lines": [
      "4"
    ]
  },
  {
    "id": "2385324651",
    "name": "Samgakji",
    "nameKo": "삼각지",
    "lat": 37.5344579,
    "lng": 126.9729031,
    "lines": [
      "4",
      "6"
    ]
  },
  {
    "id": "355173105",
    "name": "Sinyongsan",
    "nameKo": "신용산",
    "lat": 37.5291568,
    "lng": 126.9678072,
    "lines": [
      "4"
    ]
  },
  {
    "id": "2533971240",
    "name": "Ichon (National Museum of Korea)",
    "nameKo": "이촌",
    "lat": 37.5226181,
    "lng": 126.9736117,
    "lines": [
      "4",
      "gyeongui"
    ]
  },
  {
    "id": "798558661",
    "name": "Dongjak",
    "nameKo": "동작",
    "lat": 37.5021191,
    "lng": 126.9808291,
    "lines": [
      "4",
      "9"
    ]
  },
  {
    "id": "6036160364",
    "name": "Chongsin Univ. (Isu)",
    "nameKo": "총신대입구",
    "lat": 37.487026,
    "lng": 126.9822046,
    "lines": [
      "4"
    ]
  },
  {
    "id": "9357694474",
    "name": "Namtaeryeong",
    "nameKo": "남태령",
    "lat": 37.463972,
    "lng": 126.9889176,
    "lines": [
      "4"
    ]
  },
  {
    "id": "6035746724",
    "name": "Seonbawi",
    "nameKo": "선바위",
    "lat": 37.4507449,
    "lng": 127.003056,
    "lines": [
      "4"
    ]
  },
  {
    "id": "6035746726",
    "name": "Seoul Racecourse park",
    "nameKo": "경마공원",
    "lat": 37.4438286,
    "lng": 127.007913,
    "lines": [
      "4"
    ]
  },
  {
    "id": "6035746710",
    "name": "Seoul Grand park",
    "nameKo": "대공원",
    "lat": 37.435088,
    "lng": 127.0061773,
    "lines": [
      "4"
    ]
  },
  {
    "id": "6035746736",
    "name": "Gwacheon",
    "nameKo": "과천",
    "lat": 37.4330278,
    "lng": 126.9968428,
    "lines": [
      "4"
    ]
  },
  {
    "id": "6035746709",
    "name": "Ansan Line",
    "nameKo": "정부과천청사",
    "lat": 37.4264288,
    "lng": 126.9897471,
    "lines": [
      "4"
    ]
  },
  {
    "id": "6035746755",
    "name": "Indeogwon",
    "nameKo": "인덕원",
    "lat": 37.4013614,
    "lng": 126.9769874,
    "lines": [
      "4"
    ]
  },
  {
    "id": "6035746765",
    "name": "Pyeongchon",
    "nameKo": "평촌",
    "lat": 37.3942706,
    "lng": 126.9638926,
    "lines": [
      "4"
    ]
  },
  {
    "id": "6035746706",
    "name": "Beomgye",
    "nameKo": "범계",
    "lat": 37.3898873,
    "lng": 126.9509188,
    "lines": [
      "4"
    ]
  },
  {
    "id": "10795263940",
    "name": "Geumjeong",
    "nameKo": "금정",
    "lat": 37.3715851,
    "lng": 126.9439463,
    "lines": [
      "1",
      "4"
    ]
  },
  {
    "id": "5347811352",
    "name": "Sanbon",
    "nameKo": "산본",
    "lat": 37.3575433,
    "lng": 126.9321639,
    "lines": [
      "4"
    ]
  },
  {
    "id": "5347802254",
    "name": "Surisan",
    "nameKo": "수리산",
    "lat": 37.3498152,
    "lng": 126.9253962,
    "lines": [
      "4"
    ]
  },
  {
    "id": "355173131",
    "name": "Daeyami",
    "nameKo": "대야미",
    "lat": 37.3272174,
    "lng": 126.9162856,
    "lines": [
      "4"
    ]
  },
  {
    "id": "4974511637",
    "name": "Banwol",
    "nameKo": "반월",
    "lat": 37.3116652,
    "lng": 126.9032326,
    "lines": [
      "4"
    ]
  },
  {
    "id": "5911861549",
    "name": "Sangnoksu",
    "nameKo": "상록수",
    "lat": 37.3028721,
    "lng": 126.8656673,
    "lines": [
      "4"
    ]
  },
  {
    "id": "5911861568",
    "name": "Hanyang University at Ansan",
    "nameKo": "한대앞",
    "lat": 37.3104519,
    "lng": 126.852888,
    "lines": [
      "4",
      "bundang"
    ]
  },
  {
    "id": "5349743239",
    "name": "Jungang",
    "nameKo": "중앙",
    "lat": 37.3160633,
    "lng": 126.8374647,
    "lines": [
      "4",
      "bundang"
    ]
  },
  {
    "id": "5911861689",
    "name": "Gojan",
    "nameKo": "고잔",
    "lat": 37.3169005,
    "lng": 126.8220934,
    "lines": [
      "4",
      "bundang"
    ]
  },
  {
    "id": "5723047769",
    "name": "Choji",
    "nameKo": "초지",
    "lat": 37.3211622,
    "lng": 126.8049024,
    "lines": [
      "4",
      "bundang"
    ]
  },
  {
    "id": "5911861708",
    "name": "Ansan",
    "nameKo": "안산",
    "lat": 37.3274089,
    "lng": 126.7879605,
    "lines": [
      "4",
      "bundang"
    ]
  },
  {
    "id": "2066387615",
    "name": "Singiloncheon",
    "nameKo": "신길온천",
    "lat": 37.3380983,
    "lng": 126.7661867,
    "lines": [
      "4",
      "bundang"
    ]
  },
  {
    "id": "619039778",
    "name": "Jeongwang",
    "nameKo": "정왕",
    "lat": 37.3520536,
    "lng": 126.7419901,
    "lines": [
      "4",
      "bundang"
    ]
  },
  {
    "id": "5907965098",
    "name": "Oido",
    "nameKo": "오이도",
    "lat": 37.3628018,
    "lng": 126.738718,
    "lines": [
      "4",
      "bundang"
    ]
  },
  {
    "id": "7872228251",
    "name": "Gosaek",
    "nameKo": "고색",
    "lat": 37.2498322,
    "lng": 126.9803937,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5910050514",
    "name": "Suwon",
    "nameKo": "수원",
    "lat": 37.266659,
    "lng": 127.0013487,
    "lines": [
      "1",
      "bundang"
    ]
  },
  {
    "id": "7287966330",
    "name": "매교",
    "nameKo": "매교",
    "lat": 37.2655001,
    "lng": 127.0157079,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7287966323",
    "name": "수원시청",
    "nameKo": "수원시청",
    "lat": 37.2617563,
    "lng": 127.0319033,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7287966313",
    "name": "매탄권선",
    "nameKo": "매탄권선",
    "lat": 37.2530511,
    "lng": 127.0404781,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7287966302",
    "name": "망포",
    "nameKo": "망포",
    "lat": 37.245644,
    "lng": 127.0570027,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7287966296",
    "name": "영통",
    "nameKo": "영통",
    "lat": 37.2513838,
    "lng": 127.0712437,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7287966289",
    "name": "청명",
    "nameKo": "청명",
    "lat": 37.2599984,
    "lng": 127.0794894,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7287965175",
    "name": "상갈",
    "nameKo": "상갈",
    "lat": 37.2617522,
    "lng": 127.1088684,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "1725220163",
    "name": "Giheung",
    "nameKo": "기흥",
    "lat": 37.2755066,
    "lng": 127.1159856,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7287965143",
    "name": "신갈",
    "nameKo": "신갈",
    "lat": 37.286116,
    "lng": 127.1113353,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7287965130",
    "name": "구성",
    "nameKo": "구성",
    "lat": 37.2990209,
    "lng": 127.1057172,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "1914727373",
    "name": "Bojeong",
    "nameKo": "보정",
    "lat": 37.3123522,
    "lng": 127.1082976,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5924431380",
    "name": "Jukjeon",
    "nameKo": "죽전",
    "lat": 37.3245639,
    "lng": 127.1073844,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5438824808",
    "name": "Ori",
    "nameKo": "오리",
    "lat": 37.3406386,
    "lng": 127.1088934,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5881397264",
    "name": "Migeum",
    "nameKo": "미금",
    "lat": 37.3499981,
    "lng": 127.1089702,
    "lines": [
      "bundang",
      "shinbundang"
    ]
  },
  {
    "id": "5225259408",
    "name": "Jeongja",
    "nameKo": "정자",
    "lat": 37.3653889,
    "lng": 127.1080933,
    "lines": [
      "bundang",
      "shinbundang"
    ]
  },
  {
    "id": "1915043095",
    "name": "Sunae",
    "nameKo": "수내",
    "lat": 37.3784199,
    "lng": 127.1142279,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "1915043090",
    "name": "Seohyeon",
    "nameKo": "서현",
    "lat": 37.3849257,
    "lng": 127.1233156,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5882162368",
    "name": "Imae",
    "nameKo": "이매",
    "lat": 37.3952494,
    "lng": 127.1282124,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "1915043091",
    "name": "Yatap",
    "nameKo": "야탑",
    "lat": 37.4112829,
    "lng": 127.1286881,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5887972151",
    "name": "Moran",
    "nameKo": "모란",
    "lat": 37.4321771,
    "lng": 127.1290618,
    "lines": [
      "8",
      "bundang"
    ]
  },
  {
    "id": "1914136597",
    "name": "Taepyeong",
    "nameKo": "태평",
    "lat": 37.4397071,
    "lng": 127.1277192,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "1914136725",
    "name": "Gachon Univ.",
    "nameKo": "가천대",
    "lat": 37.4486968,
    "lng": 127.1266971,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "4733039958",
    "name": "Bokjeong",
    "nameKo": "복정",
    "lat": 37.4716385,
    "lng": 127.1266838,
    "lines": [
      "8",
      "bundang"
    ]
  },
  {
    "id": "355173583",
    "name": "Daemosan",
    "nameKo": "대모산입구",
    "lat": 37.4913743,
    "lng": 127.0727648,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "6312484935",
    "name": "Gaepo-dong",
    "nameKo": "개포동",
    "lat": 37.4890796,
    "lng": 127.0660515,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "1906684759",
    "name": "Guryong",
    "nameKo": "구룡",
    "lat": 37.4869099,
    "lng": 127.059455,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "6312484936",
    "name": "Hanti",
    "nameKo": "한티",
    "lat": 37.496274,
    "lng": 127.0528411,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7908597444",
    "name": "Seonjeongneung",
    "nameKo": "선정릉",
    "lat": 37.510668,
    "lng": 127.0436952,
    "lines": [
      "9",
      "bundang"
    ]
  },
  {
    "id": "6312484938",
    "name": "Gangnam-gu Office",
    "nameKo": "강남구청",
    "lat": 37.5167764,
    "lng": 127.0414135,
    "lines": [
      "7",
      "bundang"
    ]
  },
  {
    "id": "6312484944",
    "name": "Apgujungrodeo",
    "nameKo": "압구정로데오",
    "lat": 37.5278201,
    "lng": 127.0406811,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "4963715631",
    "name": "Seoul-forest",
    "nameKo": "서울숲",
    "lat": 37.5436201,
    "lng": 127.0447177,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5325300810",
    "name": "Gaehwa",
    "nameKo": "개화",
    "lat": 37.5784343,
    "lng": 126.7968238,
    "lines": [
      "9"
    ]
  },
  {
    "id": "3278844040",
    "name": "Gimpo Int'l Airport",
    "nameKo": "김포공항",
    "lat": 37.5619723,
    "lng": 126.8015364,
    "lines": [
      "5",
      "9",
      "airport"
    ]
  },
  {
    "id": "1994677371",
    "name": "Airport Market",
    "nameKo": "공항시장",
    "lat": 37.5634156,
    "lng": 126.8104215,
    "lines": [
      "9"
    ]
  },
  {
    "id": "4604102197",
    "name": "Sinbanghwa",
    "nameKo": "신방화",
    "lat": 37.5674056,
    "lng": 126.8178288,
    "lines": [
      "9"
    ]
  },
  {
    "id": "1996406534",
    "name": "마곡나루",
    "nameKo": "마곡나루",
    "lat": 37.5666674,
    "lng": 126.8277135,
    "lines": [
      "9",
      "airport"
    ]
  },
  {
    "id": "1994678935",
    "name": "Yangcheon Hyanggyo",
    "nameKo": "양천향교",
    "lat": 37.5684782,
    "lng": 126.8412018,
    "lines": [
      "9"
    ]
  },
  {
    "id": "1994679616",
    "name": "Gayang",
    "nameKo": "가양",
    "lat": 37.5611258,
    "lng": 126.8550615,
    "lines": [
      "9"
    ]
  },
  {
    "id": "1994679915",
    "name": "Jeungmi",
    "nameKo": "증미",
    "lat": 37.557422,
    "lng": 126.86193,
    "lines": [
      "9"
    ]
  },
  {
    "id": "1994680293",
    "name": "Deungchon",
    "nameKo": "등촌",
    "lat": 37.5511895,
    "lng": 126.8645708,
    "lines": [
      "9"
    ]
  },
  {
    "id": "1994680392",
    "name": "Yeomchang",
    "nameKo": "염창",
    "lat": 37.5470051,
    "lng": 126.8754428,
    "lines": [
      "9"
    ]
  },
  {
    "id": "1994680522",
    "name": "Sinmokdong",
    "nameKo": "신목동",
    "lat": 37.544227,
    "lng": 126.8831853,
    "lines": [
      "9"
    ]
  },
  {
    "id": "3439039804",
    "name": "Seonyudo",
    "nameKo": "선유도",
    "lat": 37.5378557,
    "lng": 126.8938639,
    "lines": [
      "9"
    ]
  },
  {
    "id": "9181579787",
    "name": "National Assembly",
    "nameKo": "국회의사당",
    "lat": 37.5274368,
    "lng": 126.9184254,
    "lines": [
      "9"
    ]
  },
  {
    "id": "5917210895",
    "name": "여의도",
    "nameKo": "여의도",
    "lat": 37.5217071,
    "lng": 126.9241053,
    "lines": [
      "5",
      "9"
    ]
  },
  {
    "id": "9482998436",
    "name": "Saetgang",
    "nameKo": "샛강",
    "lat": 37.5172824,
    "lng": 126.9283959,
    "lines": [
      "9"
    ]
  },
  {
    "id": "1996430636",
    "name": "Noryangjin",
    "nameKo": "노량진",
    "lat": 37.5136072,
    "lng": 126.9418701,
    "lines": [
      "1",
      "9"
    ]
  },
  {
    "id": "1996430673",
    "name": "Nodeul",
    "nameKo": "노들",
    "lat": 37.5129494,
    "lng": 126.9535788,
    "lines": [
      "9"
    ]
  },
  {
    "id": "1994702763",
    "name": "Heukseok",
    "nameKo": "흑석",
    "lat": 37.508366,
    "lng": 126.9639299,
    "lines": [
      "9"
    ]
  },
  {
    "id": "1994703274",
    "name": "Gubanpo",
    "nameKo": "구반포",
    "lat": 37.5012703,
    "lng": 126.9867889,
    "lines": [
      "9"
    ]
  },
  {
    "id": "1994703290",
    "name": "Sinbanpo",
    "nameKo": "신반포",
    "lat": 37.5035801,
    "lng": 126.9964259,
    "lines": [
      "9"
    ]
  },
  {
    "id": "3824606383",
    "name": "Sapyeong",
    "nameKo": "사평",
    "lat": 37.504105,
    "lng": 127.0153773,
    "lines": [
      "9"
    ]
  },
  {
    "id": "3824606392",
    "name": "Sinnonhyeon",
    "nameKo": "신논현역",
    "lat": 37.5045465,
    "lng": 127.0248738,
    "lines": [
      "9"
    ]
  },
  {
    "id": "3454026413",
    "name": "Eonju",
    "nameKo": "언주",
    "lat": 37.5073701,
    "lng": 127.0341153,
    "lines": [
      "9"
    ]
  },
  {
    "id": "3824606380",
    "name": "Samseong Jungang",
    "nameKo": "삼성중앙",
    "lat": 37.5130743,
    "lng": 127.0537122,
    "lines": [
      "9"
    ]
  },
  {
    "id": "3824606374",
    "name": "Bongeunsa",
    "nameKo": "봉은사역",
    "lat": 37.5141546,
    "lng": 127.0601774,
    "lines": [
      "9"
    ]
  },
  {
    "id": "6117347092",
    "name": "삼전",
    "nameKo": "삼전",
    "lat": 37.504478,
    "lng": 127.0871856,
    "lines": [
      "9"
    ]
  },
  {
    "id": "6102706816",
    "name": "석촌고분",
    "nameKo": "석촌고분",
    "lat": 37.502417,
    "lng": 127.0965651,
    "lines": [
      "9"
    ]
  },
  {
    "id": "6102706788",
    "name": "Seokchon",
    "nameKo": "석촌",
    "lat": 37.5050452,
    "lng": 127.1068567,
    "lines": [
      "8",
      "9"
    ]
  },
  {
    "id": "6117347089",
    "name": "송파나루",
    "nameKo": "송파나루",
    "lat": 37.5112303,
    "lng": 127.1128828,
    "lines": [
      "9"
    ]
  },
  {
    "id": "6102706837",
    "name": "한성백제",
    "nameKo": "한성백제",
    "lat": 37.5167113,
    "lng": 127.1162809,
    "lines": [
      "9"
    ]
  },
  {
    "id": "6102706374",
    "name": "올림픽공원",
    "nameKo": "올림픽공원",
    "lat": 37.5160799,
    "lng": 127.1303019,
    "lines": [
      "5",
      "9"
    ]
  },
  {
    "id": "6102706369",
    "name": "둔촌오륜",
    "nameKo": "둔촌오륜",
    "lat": 37.5198527,
    "lng": 127.1383293,
    "lines": [
      "9"
    ]
  },
  {
    "id": "6102706367",
    "name": "VHS Medical Center",
    "nameKo": "중앙보훈병원",
    "lat": 37.5282699,
    "lng": 127.148286,
    "lines": [
      "9"
    ]
  },
  {
    "id": "12119884929",
    "name": "Byeollae",
    "nameKo": "별내",
    "lat": 37.6418028,
    "lng": 127.1280243,
    "lines": [
      "8"
    ]
  },
  {
    "id": "12119884931",
    "name": "Dasan",
    "nameKo": "다산",
    "lat": 37.6237479,
    "lng": 127.1496187,
    "lines": [
      "8"
    ]
  },
  {
    "id": "12119884932",
    "name": "Donggureung",
    "nameKo": "동구릉",
    "lat": 37.6101744,
    "lng": 127.1381349,
    "lines": [
      "8"
    ]
  },
  {
    "id": "12119884933",
    "name": "Guri",
    "nameKo": "구리",
    "lat": 37.6016366,
    "lng": 127.1410186,
    "lines": [
      "8",
      "gyeongui"
    ]
  },
  {
    "id": "8445537865",
    "name": "Jangja Lake Park",
    "nameKo": "장자호수공원",
    "lat": 37.5864905,
    "lng": 127.1378478,
    "lines": [
      "8"
    ]
  },
  {
    "id": "8445537827",
    "name": "Amsa History Park",
    "nameKo": "암사역사공원",
    "lat": 37.5568968,
    "lng": 127.1365133,
    "lines": [
      "8"
    ]
  },
  {
    "id": "355173473",
    "name": "Amsa",
    "nameKo": "암사",
    "lat": 37.5490025,
    "lng": 127.1270746,
    "lines": [
      "8"
    ]
  },
  {
    "id": "5801302006",
    "name": "Cheonho",
    "nameKo": "천호",
    "lat": 37.5380736,
    "lng": 127.1232037,
    "lines": [
      "5",
      "8"
    ]
  },
  {
    "id": "414685028",
    "name": "Gangdong-gu Office",
    "nameKo": "강동구청",
    "lat": 37.5306815,
    "lng": 127.120598,
    "lines": [
      "8"
    ]
  },
  {
    "id": "414684814",
    "name": "Mongchontoseong",
    "nameKo": "몽촌토성",
    "lat": 37.5175496,
    "lng": 127.1126502,
    "lines": [
      "8"
    ]
  },
  {
    "id": "355173581",
    "name": "Songpa",
    "nameKo": "송파",
    "lat": 37.4996207,
    "lng": 127.1122514,
    "lines": [
      "8"
    ]
  },
  {
    "id": "355173577",
    "name": "Munjeong",
    "nameKo": "문정",
    "lat": 37.48585,
    "lng": 127.122484,
    "lines": [
      "8"
    ]
  },
  {
    "id": "5821684795",
    "name": "Jangji",
    "nameKo": "장지",
    "lat": 37.4788927,
    "lng": 127.1260371,
    "lines": [
      "8"
    ]
  },
  {
    "id": "3605365336",
    "name": "Namwirye",
    "nameKo": "남위례",
    "lat": 37.4624724,
    "lng": 127.1397967,
    "lines": [
      "8"
    ]
  },
  {
    "id": "355173569",
    "name": "Sanseong",
    "nameKo": "산성",
    "lat": 37.4568481,
    "lng": 127.1499078,
    "lines": [
      "8"
    ]
  },
  {
    "id": "4809472051",
    "name": "Namhansanseong",
    "nameKo": "남한산성입구",
    "lat": 37.451584,
    "lng": 127.159804,
    "lines": [
      "8"
    ]
  },
  {
    "id": "355173593",
    "name": "Dandaeogeori",
    "nameKo": "단대오거리",
    "lat": 37.4450934,
    "lng": 127.1567551,
    "lines": [
      "8"
    ]
  },
  {
    "id": "355173595",
    "name": "Sinheung",
    "nameKo": "신흥",
    "lat": 37.4410138,
    "lng": 127.1476254,
    "lines": [
      "8"
    ]
  },
  {
    "id": "355173590",
    "name": "Sujin",
    "nameKo": "수진",
    "lat": 37.4374574,
    "lng": 127.1406647,
    "lines": [
      "8"
    ]
  },
  {
    "id": "5919544837",
    "name": "Incheon Airport Terminal 2",
    "nameKo": "인천공항2터미널",
    "lat": 37.4688911,
    "lng": 126.4334999,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5919544824",
    "name": "Incheon Int'l Airport Terminal 1",
    "nameKo": "인천공항1터미널",
    "lat": 37.4472569,
    "lng": 126.4526977,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5919544815",
    "name": "공항화물청사",
    "nameKo": "공항화물청사",
    "lat": 37.4589066,
    "lng": 126.4776332,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5919544811",
    "name": "운서",
    "nameKo": "운서",
    "lat": 37.4928102,
    "lng": 126.4937351,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5919544751",
    "name": "영종",
    "nameKo": "영종",
    "lat": 37.5120219,
    "lng": 126.5248572,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5919544740",
    "name": "청라국제도시",
    "nameKo": "청라국제도시",
    "lat": 37.5565025,
    "lng": 126.6246726,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5919544723",
    "name": "검암",
    "nameKo": "검암",
    "lat": 37.5691612,
    "lng": 126.6736778,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5204025132",
    "name": "Gyeyang",
    "nameKo": "계양",
    "lat": 37.5717906,
    "lng": 126.7363487,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5919544689",
    "name": "Gongdeok",
    "nameKo": "공덕",
    "lat": 37.5424161,
    "lng": 126.9522541,
    "lines": [
      "5",
      "6",
      "airport",
      "gyeongui"
    ]
  },
  {
    "id": "5916874386",
    "name": "응암",
    "nameKo": "응암",
    "lat": 37.598774,
    "lng": 126.9157018,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173383",
    "name": "역촌",
    "nameKo": "역촌",
    "lat": 37.6060541,
    "lng": 126.9228008,
    "lines": [
      "6"
    ]
  },
  {
    "id": "6041674928",
    "name": "독바위",
    "nameKo": "독바위",
    "lat": 37.6184519,
    "lng": 126.9330576,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173384",
    "name": "구산",
    "nameKo": "구산",
    "lat": 37.6110401,
    "lng": 126.9170995,
    "lines": [
      "6"
    ]
  },
  {
    "id": "414683380",
    "name": "Saejeol",
    "nameKo": "새절",
    "lat": 37.5910867,
    "lng": 126.9134797,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173381",
    "name": "증산",
    "nameKo": "증산",
    "lat": 37.5841289,
    "lng": 126.9098598,
    "lines": [
      "6"
    ]
  },
  {
    "id": "5919544688",
    "name": "Digital Media City",
    "nameKo": "디지털미디어시티",
    "lat": 37.576216,
    "lng": 126.9014392,
    "lines": [
      "6",
      "gyeongui"
    ]
  },
  {
    "id": "355173429",
    "name": "월드컵경기장",
    "nameKo": "월드컵경기장",
    "lat": 37.5701609,
    "lng": 126.8992939,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173424",
    "name": "마포구청",
    "nameKo": "마포구청",
    "lat": 37.5635156,
    "lng": 126.9033737,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173426",
    "name": "망원",
    "nameKo": "망원",
    "lat": 37.5559808,
    "lng": 126.9101224,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173436",
    "name": "상수",
    "nameKo": "상수",
    "lat": 37.5477391,
    "lng": 126.9229225,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173431",
    "name": "광흥창",
    "nameKo": "광흥창",
    "lat": 37.547449,
    "lng": 126.932001,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173433",
    "name": "대흥",
    "nameKo": "대흥",
    "lat": 37.5476895,
    "lng": 126.9423171,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173443",
    "name": "Hyochang Park",
    "nameKo": "효창공원앞",
    "lat": 37.5393117,
    "lng": 126.9613534,
    "lines": [
      "6",
      "gyeongui"
    ]
  },
  {
    "id": "355173438",
    "name": "녹사평",
    "nameKo": "녹사평",
    "lat": 37.5347329,
    "lng": 126.9864975,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173440",
    "name": "이태원",
    "nameKo": "이태원",
    "lat": 37.534481,
    "lng": 126.994386,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173448",
    "name": "한강진",
    "nameKo": "한강진",
    "lat": 37.5398199,
    "lng": 127.0017633,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173451",
    "name": "버티고개",
    "nameKo": "버티고개",
    "lat": 37.5482256,
    "lng": 127.0066769,
    "lines": [
      "6"
    ]
  },
  {
    "id": "6039313640",
    "name": "청구",
    "nameKo": "청구",
    "lat": 37.5602864,
    "lng": 127.0138544,
    "lines": [
      "5",
      "6"
    ]
  },
  {
    "id": "3279010922",
    "name": "Dongmyo",
    "nameKo": "동묘앞",
    "lat": 37.571413,
    "lng": 127.0158026,
    "lines": [
      "1",
      "6"
    ]
  },
  {
    "id": "355173402",
    "name": "창신",
    "nameKo": "창신",
    "lat": 37.579786,
    "lng": 127.015273,
    "lines": [
      "6"
    ]
  },
  {
    "id": "5747397251",
    "name": "Bomun",
    "nameKo": "보문",
    "lat": 37.5852622,
    "lng": 127.0193326,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173400",
    "name": "안암",
    "nameKo": "안암",
    "lat": 37.5862818,
    "lng": 127.029329,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173408",
    "name": "Korea Univ.",
    "nameKo": "고려대",
    "lat": 37.58975,
    "lng": 127.0359359,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173406",
    "name": "월곡",
    "nameKo": "월곡",
    "lat": 37.601924,
    "lng": 127.041489,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173405",
    "name": "상월곡",
    "nameKo": "상월곡",
    "lat": 37.606207,
    "lng": 127.0482569,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173404",
    "name": "돌곶이",
    "nameKo": "돌곶이",
    "lat": 37.6105343,
    "lng": 127.0564905,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355172774",
    "name": "Seokgye",
    "nameKo": "석계",
    "lat": 37.6148757,
    "lng": 127.065768,
    "lines": [
      "1",
      "6"
    ]
  },
  {
    "id": "6041673025",
    "name": "태릉입구",
    "nameKo": "태릉입구",
    "lat": 37.6172248,
    "lng": 127.0745285,
    "lines": [
      "6",
      "7"
    ]
  },
  {
    "id": "355173413",
    "name": "화랑대",
    "nameKo": "화랑대",
    "lat": 37.6197559,
    "lng": 127.0837172,
    "lines": [
      "6"
    ]
  },
  {
    "id": "355173411",
    "name": "Bonghwasan",
    "nameKo": "봉화산",
    "lat": 37.6173928,
    "lng": 127.0910747,
    "lines": [
      "6"
    ]
  },
  {
    "id": "8049297383",
    "name": "Sinseol-dong",
    "nameKo": "신설동",
    "lat": 37.5740982,
    "lng": 127.0263347,
    "lines": [
      "1",
      "2"
    ]
  },
  {
    "id": "355172924",
    "name": "용두",
    "nameKo": "용두",
    "lat": 37.5738711,
    "lng": 127.038702,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5694832466",
    "name": "신답",
    "nameKo": "신답",
    "lat": 37.5692823,
    "lng": 127.0474214,
    "lines": [
      "2"
    ]
  },
  {
    "id": "5856128334",
    "name": "용답",
    "nameKo": "용답",
    "lat": 37.5617246,
    "lng": 127.0510125,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033364547",
    "name": "Dorimcheon",
    "nameKo": "도림천",
    "lat": 37.5144991,
    "lng": 126.8826324,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033364507",
    "name": "Yangcheon-gu Office",
    "nameKo": "양천구청",
    "lat": 37.5123003,
    "lng": 126.8659115,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033364446",
    "name": "Sinjeongnegeori",
    "nameKo": "신정네거리",
    "lat": 37.5200245,
    "lng": 126.853057,
    "lines": [
      "2"
    ]
  },
  {
    "id": "6033364443",
    "name": "Kkachisan",
    "nameKo": "까치산",
    "lat": 37.5313676,
    "lng": 126.846698,
    "lines": [
      "2",
      "5"
    ]
  },
  {
    "id": "6039313057",
    "name": "마천",
    "nameKo": "마천",
    "lat": 37.4949893,
    "lng": 127.1527509,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6039313046",
    "name": "거여",
    "nameKo": "거여",
    "lat": 37.4933801,
    "lng": 127.1437715,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6039313049",
    "name": "개롱",
    "nameKo": "개롱",
    "lat": 37.4981053,
    "lng": 127.1348455,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6039313053",
    "name": "방이",
    "nameKo": "방이",
    "lat": 37.5086178,
    "lng": 127.1260719,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6039313073",
    "name": "둔촌동",
    "nameKo": "둔촌동",
    "lat": 37.5277875,
    "lng": 127.1362849,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6039313082",
    "name": "강동",
    "nameKo": "강동",
    "lat": 37.5358634,
    "lng": 127.1326384,
    "lines": [
      "5"
    ]
  },
  {
    "id": "5915757374",
    "name": "Sangil-dong",
    "nameKo": "상일동",
    "lat": 37.5566609,
    "lng": 127.1650911,
    "lines": [
      "5"
    ]
  },
  {
    "id": "5915757375",
    "name": "Godeok",
    "nameKo": "고덕",
    "lat": 37.5550028,
    "lng": 127.1537873,
    "lines": [
      "5"
    ]
  },
  {
    "id": "5915757377",
    "name": "명일",
    "nameKo": "명일",
    "lat": 37.5519248,
    "lng": 127.1440529,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173312",
    "name": "굽은다리",
    "nameKo": "굽은다리",
    "lat": 37.5456603,
    "lng": 127.1429306,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173323",
    "name": "길동",
    "nameKo": "길동",
    "lat": 37.5383553,
    "lng": 127.140159,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173377",
    "name": "광나루",
    "nameKo": "광나루",
    "lat": 37.5453332,
    "lng": 127.1035169,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173375",
    "name": "아차산",
    "nameKo": "아차산",
    "lat": 37.5517023,
    "lng": 127.0898223,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6039313614",
    "name": "군자",
    "nameKo": "군자",
    "lat": 37.5571693,
    "lng": 127.0795654,
    "lines": [
      "5",
      "7"
    ]
  },
  {
    "id": "355173372",
    "name": "장한평",
    "nameKo": "장한평",
    "lat": 37.5615078,
    "lng": 127.0645955,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173370",
    "name": "답십리",
    "nameKo": "답십리",
    "lat": 37.5668495,
    "lng": 127.0527067,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173368",
    "name": "마장",
    "nameKo": "마장",
    "lat": 37.5661188,
    "lng": 127.0428899,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173365",
    "name": "행당",
    "nameKo": "행당",
    "lat": 37.5576032,
    "lng": 127.0299451,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173364",
    "name": "신금호",
    "nameKo": "신금호",
    "lat": 37.5544558,
    "lng": 127.0202666,
    "lines": [
      "5"
    ]
  },
  {
    "id": "2346858819",
    "name": "Gwanghwamun",
    "nameKo": "광화문",
    "lat": 37.5716332,
    "lng": 126.9769142,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173360",
    "name": "서대문",
    "nameKo": "서대문",
    "lat": 37.5658085,
    "lng": 126.9666095,
    "lines": [
      "5"
    ]
  },
  {
    "id": "3278844465",
    "name": "애오개",
    "nameKo": "애오개",
    "lat": 37.553447,
    "lng": 126.9566713,
    "lines": [
      "5"
    ]
  },
  {
    "id": "353186877",
    "name": "마포",
    "nameKo": "마포",
    "lat": 37.5396405,
    "lng": 126.9459579,
    "lines": [
      "5"
    ]
  },
  {
    "id": "414684925",
    "name": "여의나루",
    "nameKo": "여의나루",
    "lat": 37.5268661,
    "lng": 126.9325101,
    "lines": [
      "5"
    ]
  },
  {
    "id": "2803508740",
    "name": "Singil",
    "nameKo": "신길",
    "lat": 37.5175712,
    "lng": 126.9165959,
    "lines": [
      "1",
      "5"
    ]
  },
  {
    "id": "6039313681",
    "name": "영등포시장",
    "nameKo": "영등포시장",
    "lat": 37.5227195,
    "lng": 126.9051311,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6039313985",
    "name": "Yangpyeong",
    "nameKo": "양평",
    "lat": 37.525654,
    "lng": 126.886125,
    "lines": [
      "5",
      "gyeongui"
    ]
  },
  {
    "id": "355173398",
    "name": "Omokgyo",
    "nameKo": "오목교",
    "lat": 37.5245758,
    "lng": 126.8751578,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173399",
    "name": "Mok-dong",
    "nameKo": "목동",
    "lat": 37.5261412,
    "lng": 126.864513,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6039313995",
    "name": "Sinjeong",
    "nameKo": "신정",
    "lat": 37.5250652,
    "lng": 126.8559381,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173397",
    "name": "Hwagok",
    "nameKo": "화곡",
    "lat": 37.5417123,
    "lng": 126.8404024,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6039314019",
    "name": "Ujangsan",
    "nameKo": "우장산",
    "lat": 37.5488674,
    "lng": 126.8363427,
    "lines": [
      "5"
    ]
  },
  {
    "id": "1790506663",
    "name": "Balsan",
    "nameKo": "발산",
    "lat": 37.5584571,
    "lng": 126.8375125,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173390",
    "name": "Magok",
    "nameKo": "마곡",
    "lat": 37.5602708,
    "lng": 126.8247446,
    "lines": [
      "5"
    ]
  },
  {
    "id": "1790519133",
    "name": "Songjeong",
    "nameKo": "송정",
    "lat": 37.5612892,
    "lng": 126.8119992,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6039314031",
    "name": "Gaehwasan",
    "nameKo": "개화산",
    "lat": 37.5728374,
    "lng": 126.808166,
    "lines": [
      "5"
    ]
  },
  {
    "id": "355173386",
    "name": "방화",
    "nameKo": "방화",
    "lat": 37.5773845,
    "lng": 126.8127722,
    "lines": [
      "5"
    ]
  },
  {
    "id": "5773411578",
    "name": "Gwangmyeong",
    "nameKo": "광명",
    "lat": 37.4169851,
    "lng": 126.8846994,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3153793711",
    "name": "Geumcheon-gu Office",
    "nameKo": "금천구청",
    "lat": 37.4563959,
    "lng": 126.8934833,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3426723670",
    "name": "Doksan",
    "nameKo": "독산",
    "lat": 37.4668796,
    "lng": 126.8890361,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3426723651",
    "name": "Gasan Digital Complex",
    "nameKo": "가산디지털단지",
    "lat": 37.4823798,
    "lng": 126.8821636,
    "lines": [
      "1",
      "7"
    ]
  },
  {
    "id": "5896638402",
    "name": "Guro",
    "nameKo": "구로",
    "lat": 37.5033463,
    "lng": 126.8823678,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3212614903",
    "name": "Yeongdeungpo",
    "nameKo": "영등포",
    "lat": 37.5154485,
    "lng": 126.9072862,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5889532187",
    "name": "Yongmun",
    "nameKo": "용문",
    "lat": 37.4820467,
    "lng": 127.5947947,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5889532072",
    "name": "원덕",
    "nameKo": "원덕",
    "lat": 37.4689667,
    "lng": 127.5454542,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5889529470",
    "name": "오빈",
    "nameKo": "오빈",
    "lat": 37.5064442,
    "lng": 127.4726689,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5889529458",
    "name": "Asin",
    "nameKo": "아신",
    "lat": 37.5141696,
    "lng": 127.4421485,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5889529441",
    "name": "국수",
    "nameKo": "국수",
    "lat": 37.5159075,
    "lng": 127.3982455,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5889529431",
    "name": "신원",
    "nameKo": "신원",
    "lat": 37.5262402,
    "lng": 127.3724619,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890164147",
    "name": "양수",
    "nameKo": "양수",
    "lat": 37.5464099,
    "lng": 127.3281417,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890164134",
    "name": "운길산",
    "nameKo": "운길산",
    "lat": 37.555176,
    "lng": 127.308969,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890164130",
    "name": "팔당",
    "nameKo": "팔당",
    "lat": 37.5481215,
    "lng": 127.2429811,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890637513",
    "name": "도심",
    "nameKo": "도심",
    "lat": 37.5798815,
    "lng": 127.2217583,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890637492",
    "name": "덕소",
    "nameKo": "덕소",
    "lat": 37.5875186,
    "lng": 127.2076604,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "4063596085",
    "name": "양정",
    "nameKo": "양정",
    "lat": 37.6046783,
    "lng": 127.1941174,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5519310088",
    "name": "Donong",
    "nameKo": "도농",
    "lat": 37.6087773,
    "lng": 127.1612194,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890637453",
    "name": "양원",
    "nameKo": "양원",
    "lat": 37.6064164,
    "lng": 127.1072307,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5571709416",
    "name": "Mangu",
    "nameKo": "망우",
    "lat": 37.5989729,
    "lng": 127.0915707,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890637419",
    "name": "상봉",
    "nameKo": "상봉",
    "lat": 37.5965559,
    "lng": 127.0843139,
    "lines": [
      "7",
      "gyeongui"
    ]
  },
  {
    "id": "5890637409",
    "name": "중랑",
    "nameKo": "중랑",
    "lat": 37.5946995,
    "lng": 127.0753534,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5887905550",
    "name": "Hoegi",
    "nameKo": "회기",
    "lat": 37.5891676,
    "lng": 127.0572961,
    "lines": [
      "1",
      "gyeongui"
    ]
  },
  {
    "id": "8390160499",
    "name": "Cheongnyangni (University of Seoul)",
    "nameKo": "청량리",
    "lat": 37.5806416,
    "lng": 127.0482186,
    "lines": [
      "1",
      "bundang",
      "gyeongui"
    ]
  },
  {
    "id": "5890636978",
    "name": "응봉",
    "nameKo": "응봉",
    "lat": 37.549548,
    "lng": 127.0342619,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5893030216",
    "name": "한남",
    "nameKo": "한남",
    "lat": 37.5291501,
    "lng": 127.0085345,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5893030217",
    "name": "서빙고",
    "nameKo": "서빙고",
    "lat": 37.5195173,
    "lng": 126.9872817,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5893030219",
    "name": "Yongsan",
    "nameKo": "용산",
    "lat": 37.5305621,
    "lng": 126.9663678,
    "lines": [
      "1",
      "gyeongui"
    ]
  },
  {
    "id": "4704699992",
    "name": "Sogang Univ.",
    "nameKo": "서강대",
    "lat": 37.5529911,
    "lng": 126.93427,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5893030243",
    "name": "가좌",
    "nameKo": "가좌",
    "lat": 37.5688469,
    "lng": 126.9141529,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "4151479522",
    "name": "Susaek",
    "nameKo": "수색",
    "lat": 37.5809734,
    "lng": 126.8950228,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5891334845",
    "name": "Korea Aerospace Univ.",
    "nameKo": "한국항공대",
    "lat": 37.6032316,
    "lng": 126.8677587,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5893288218",
    "name": "강매",
    "nameKo": "강매",
    "lat": 37.6121383,
    "lng": 126.8442848,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "8334213085",
    "name": "행신",
    "nameKo": "행신",
    "lat": 37.611993,
    "lng": 126.8341887,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "8334213103",
    "name": "능곡",
    "nameKo": "능곡",
    "lat": 37.619355,
    "lng": 126.8197461,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5891336948",
    "name": "Goksan",
    "nameKo": "곡산",
    "lat": 37.6463771,
    "lng": 126.8014149,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5891337012",
    "name": "Pungsan",
    "nameKo": "풍산",
    "lat": 37.6728688,
    "lng": 126.7859221,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5891337061",
    "name": "Ilsan",
    "nameKo": "일산",
    "lat": 37.682014,
    "lng": 126.7698544,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5891337069",
    "name": "탄현",
    "nameKo": "탄현",
    "lat": 37.6946855,
    "lng": 126.761013,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5891337071",
    "name": "Yadang",
    "nameKo": "야당",
    "lat": 37.7132647,
    "lng": 126.7616058,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "10743068855",
    "name": "Unjeong",
    "nameKo": "운정",
    "lat": 37.7262417,
    "lng": 126.7674433,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "4045715667",
    "name": "금릉",
    "nameKo": "금릉",
    "lat": 37.7518897,
    "lng": 126.7650266,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890815212",
    "name": "금촌",
    "nameKo": "금촌",
    "lat": 37.7665998,
    "lng": 126.7753589,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890815220",
    "name": "월롱",
    "nameKo": "월롱",
    "lat": 37.7974275,
    "lng": 126.7930258,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890815486",
    "name": "파주",
    "nameKo": "파주",
    "lat": 37.8157295,
    "lng": 126.7922097,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5890815514",
    "name": "문산",
    "nameKo": "문산",
    "lat": 37.8553067,
    "lng": 126.7879894,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "5891336974",
    "name": "Baengma",
    "nameKo": "백마",
    "lat": 37.6575978,
    "lng": 126.7949216,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "7287842392",
    "name": "Nonhyeon",
    "nameKo": "논현",
    "lat": 37.5099469,
    "lng": 127.0218958,
    "lines": [
      "7",
      "shinbundang"
    ]
  },
  {
    "id": "9776192970",
    "name": "Sinnonhyeon",
    "nameKo": "신논현",
    "lat": 37.5035711,
    "lng": 127.0249157,
    "lines": [
      "9",
      "shinbundang"
    ]
  },
  {
    "id": "1906756417",
    "name": "Yangjae Citizen's Forest",
    "nameKo": "양재시민의숲",
    "lat": 37.4701433,
    "lng": 127.0383592,
    "lines": [
      "shinbundang"
    ]
  },
  {
    "id": "1906756403",
    "name": "Cheonggyesan",
    "nameKo": "청계산입구",
    "lat": 37.4483921,
    "lng": 127.0545673,
    "lines": [
      "shinbundang"
    ]
  },
  {
    "id": "5624997112",
    "name": "Pangyo",
    "nameKo": "판교",
    "lat": 37.3943639,
    "lng": 127.1111873,
    "lines": [
      "shinbundang"
    ]
  },
  {
    "id": "4820118359",
    "name": "Dongcheon",
    "nameKo": "동천",
    "lat": 37.3378769,
    "lng": 127.1028482,
    "lines": [
      "shinbundang"
    ]
  },
  {
    "id": "6269743768",
    "name": "Suji-gu Office",
    "nameKo": "수지구청",
    "lat": 37.3224903,
    "lng": 127.0947567,
    "lines": [
      "shinbundang"
    ]
  },
  {
    "id": "6152750623",
    "name": "Seongbok",
    "nameKo": "성복",
    "lat": 37.3134135,
    "lng": 127.0803106,
    "lines": [
      "shinbundang"
    ]
  },
  {
    "id": "3492346917",
    "name": "Sanghyeon",
    "nameKo": "상현",
    "lat": 37.2974137,
    "lng": 127.0693373,
    "lines": [
      "shinbundang"
    ]
  },
  {
    "id": "3642451903",
    "name": "Gwanggyo Jungang",
    "nameKo": "광교중앙",
    "lat": 37.288547,
    "lng": 127.0514993,
    "lines": [
      "shinbundang"
    ]
  },
  {
    "id": "3740158509",
    "name": "Gwanggyo",
    "nameKo": "광교",
    "lat": 37.3024813,
    "lng": 127.0435221,
    "lines": [
      "shinbundang"
    ]
  },
  {
    "id": "11433141478",
    "name": "Soyosan",
    "nameKo": "소요산",
    "lat": 37.9471617,
    "lng": 127.0607225,
    "lines": [
      "1"
    ]
  },
  {
    "id": "4881356285",
    "name": "Dongducheon",
    "nameKo": "동두천",
    "lat": 37.9266917,
    "lng": 127.0550196,
    "lines": [
      "1"
    ]
  },
  {
    "id": "4937987035",
    "name": "Bosan",
    "nameKo": "보산",
    "lat": 37.9133009,
    "lng": 127.0573342,
    "lines": [
      "1"
    ]
  },
  {
    "id": "4937987051",
    "name": "Dongducheonjungang (Shinhan University Campus 2)",
    "nameKo": "동두천중앙",
    "lat": 37.9008562,
    "lng": 127.0564914,
    "lines": [
      "1"
    ]
  },
  {
    "id": "4939679013",
    "name": "Jihaeng",
    "nameKo": "지행",
    "lat": 37.8915262,
    "lng": 127.0557765,
    "lines": [
      "1"
    ]
  },
  {
    "id": "4939679248",
    "name": "Deokjeong (Seojeong College)",
    "nameKo": "덕정",
    "lat": 37.8424204,
    "lng": 127.0616808,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5050088095",
    "name": "Deokgye",
    "nameKo": "덕계",
    "lat": 37.8179643,
    "lng": 127.0564018,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5050088100",
    "name": "Yangju",
    "nameKo": "양주",
    "lat": 37.7733153,
    "lng": 127.0447041,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5050088102",
    "name": "Nogyang",
    "nameKo": "녹양",
    "lat": 37.758501,
    "lng": 127.042323,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5050088115",
    "name": "Ganeung",
    "nameKo": "가능",
    "lat": 37.7476557,
    "lng": 127.0447039,
    "lines": [
      "1"
    ]
  },
  {
    "id": "7121505500",
    "name": "Uijeongbu",
    "nameKo": "의정부",
    "lat": 37.7366367,
    "lng": 127.0464268,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5350784134",
    "name": "Hoeryong",
    "nameKo": "회룡",
    "lat": 37.7230757,
    "lng": 127.0472403,
    "lines": [
      "1"
    ]
  },
  {
    "id": "4520040946",
    "name": "Mangwolsa (Shinhan University)",
    "nameKo": "망월사",
    "lat": 37.7094036,
    "lng": 127.047594,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5899116546",
    "name": "Dobongsan",
    "nameKo": "도봉산",
    "lat": 37.688786,
    "lng": 127.0461858,
    "lines": [
      "1",
      "7"
    ]
  },
  {
    "id": "5899116544",
    "name": "Dobong",
    "nameKo": "도봉",
    "lat": 37.6781766,
    "lng": 127.0453853,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5899116539",
    "name": "Banghak (Dobong-gu Office)",
    "nameKo": "방학",
    "lat": 37.666534,
    "lng": 127.0444265,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5899116510",
    "name": "Nokcheon",
    "nameKo": "녹천",
    "lat": 37.6439844,
    "lng": 127.0516865,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5899214148",
    "name": "Wolgye (Induk University)",
    "nameKo": "월계",
    "lat": 37.6323154,
    "lng": 127.0588626,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5899214142",
    "name": "Kwangwoon University",
    "nameKo": "광운대",
    "lat": 37.6232033,
    "lng": 127.0620693,
    "lines": [
      "1"
    ]
  },
  {
    "id": "4246459937",
    "name": "Sinimun (Korea National University of Arts)",
    "nameKo": "신이문",
    "lat": 37.600931,
    "lng": 127.0669802,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5899527479",
    "name": "Hankuk University of Foreign Studies",
    "nameKo": "외대앞",
    "lat": 37.5956329,
    "lng": 127.063374,
    "lines": [
      "1"
    ]
  },
  {
    "id": "7611776393",
    "name": "Jegidong",
    "nameKo": "제기동",
    "lat": 37.5783087,
    "lng": 127.0335456,
    "lines": [
      "1"
    ]
  },
  {
    "id": "355172742",
    "name": "Jongno 5(o)-ga",
    "nameKo": "종로5가",
    "lat": 37.5709298,
    "lng": 127.0011763,
    "lines": [
      "1"
    ]
  },
  {
    "id": "660871450",
    "name": "Jonggak",
    "nameKo": "종각",
    "lat": 37.5701195,
    "lng": 126.9821118,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5835544503",
    "name": "Namyeong",
    "nameKo": "남영",
    "lat": 37.5395691,
    "lng": 126.9714083,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3214007453",
    "name": "Daebang",
    "nameKo": "대방",
    "lat": 37.5134068,
    "lng": 126.9254113,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5900500358",
    "name": "Guil",
    "nameKo": "구일",
    "lat": 37.4957217,
    "lng": 126.8689185,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5900500349",
    "name": "Gaebong",
    "nameKo": "개봉",
    "lat": 37.4945762,
    "lng": 126.8581644,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3174423993",
    "name": "Oryu-dong",
    "nameKo": "오류동",
    "lat": 37.4939856,
    "lng": 126.8434437,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5814312744",
    "name": "Onsu",
    "nameKo": "온수",
    "lat": 37.4919928,
    "lng": 126.8229565,
    "lines": [
      "1",
      "7"
    ]
  },
  {
    "id": "5900500328",
    "name": "Yeokgok",
    "nameKo": "역곡",
    "lat": 37.4848544,
    "lng": 126.8111076,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5900500318",
    "name": "Sosa",
    "nameKo": "소사",
    "lat": 37.4826204,
    "lng": 126.7946398,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5900500302",
    "name": "Bucheon",
    "nameKo": "부천",
    "lat": 37.4841939,
    "lng": 126.7813237,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5904751236",
    "name": "Jung-dong",
    "nameKo": "중동",
    "lat": 37.4867408,
    "lng": 126.7630781,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5902086894",
    "name": "Songnae",
    "nameKo": "송내",
    "lat": 37.4876022,
    "lng": 126.7516291,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5902086886",
    "name": "Bugae",
    "nameKo": "부개",
    "lat": 37.4884186,
    "lng": 126.7398397,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5585685809",
    "name": "Bupyeong",
    "nameKo": "부평",
    "lat": 37.4893315,
    "lng": 126.7245079,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5902086070",
    "name": "Baegun",
    "nameKo": "백운",
    "lat": 37.4824022,
    "lng": 126.7063864,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5902086062",
    "name": "Dongam",
    "nameKo": "동암",
    "lat": 37.4699087,
    "lng": 126.7029777,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5902086056",
    "name": "Ganseok",
    "nameKo": "간석",
    "lat": 37.4645678,
    "lng": 126.6924772,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5902086048",
    "name": "Juan",
    "nameKo": "주안",
    "lat": 37.4650755,
    "lng": 126.6784288,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3216255723",
    "name": "Dohwa",
    "nameKo": "도화",
    "lat": 37.4660994,
    "lng": 126.6674091,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5902086034",
    "name": "Jemulpo",
    "nameKo": "제물포",
    "lat": 37.4666952,
    "lng": 126.6565865,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5902086026",
    "name": "Dowon",
    "nameKo": "도원",
    "lat": 37.469062,
    "lng": 126.6416049,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5902086016",
    "name": "Dongincheon",
    "nameKo": "동인천",
    "lat": 37.4756163,
    "lng": 126.63231,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5902085994",
    "name": "Incheon",
    "nameKo": "인천",
    "lat": 37.4764189,
    "lng": 126.6169985,
    "lines": [
      "1",
      "bundang"
    ]
  },
  {
    "id": "5896638408",
    "name": "Seoksu",
    "nameKo": "석수",
    "lat": 37.4345411,
    "lng": 126.9025637,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5896638413",
    "name": "Gwanak",
    "nameKo": "관악",
    "lat": 37.4191207,
    "lng": 126.9090056,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5896638421",
    "name": "Anyang",
    "nameKo": "안양",
    "lat": 37.4006749,
    "lng": 126.9238319,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3426723675",
    "name": "Myeonghak",
    "nameKo": "명학",
    "lat": 37.3837522,
    "lng": 126.93601,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3426723656",
    "name": "Gunpo",
    "nameKo": "군포",
    "lat": 37.3534284,
    "lng": 126.9485985,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3426723663",
    "name": "Dangjeong",
    "nameKo": "당정",
    "lat": 37.3424456,
    "lng": 126.9484387,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3426724594",
    "name": "Uiwang",
    "nameKo": "의왕",
    "lat": 37.3193973,
    "lng": 126.9482854,
    "lines": [
      "1"
    ]
  },
  {
    "id": "3426723681",
    "name": "Sungkyunkwan University",
    "nameKo": "성균관대",
    "lat": 37.3003127,
    "lng": 126.972123,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5896399353",
    "name": "Hwaseo",
    "nameKo": "화서",
    "lat": 37.2833438,
    "lng": 126.9900975,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5896399383",
    "name": "Seryu",
    "nameKo": "세류",
    "lat": 37.2433133,
    "lng": 127.014239,
    "lines": [
      "1"
    ]
  },
  {
    "id": "4954074038",
    "name": "Byeongjeom",
    "nameKo": "병점",
    "lat": 37.2065157,
    "lng": 127.0335067,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5896284769",
    "name": "Sema",
    "nameKo": "세마",
    "lat": 37.1864677,
    "lng": 127.0439663,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5304357332",
    "name": "Osan College",
    "nameKo": "오산대",
    "lat": 37.1687277,
    "lng": 127.0633372,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5304357345",
    "name": "Osan",
    "nameKo": "오산",
    "lat": 37.1438724,
    "lng": 127.0666675,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5896286321",
    "name": "Jinwi",
    "nameKo": "진위",
    "lat": 37.109307,
    "lng": 127.0623878,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5896286341",
    "name": "Songtan",
    "nameKo": "송탄",
    "lat": 37.075606,
    "lng": 127.0544205,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5304357423",
    "name": "Seojeong-ri",
    "nameKo": "서정리",
    "lat": 37.0556777,
    "lng": 127.0528971,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5304357449",
    "name": "Pyeongtaek Jije",
    "nameKo": "평택지제",
    "lat": 37.0182009,
    "lng": 127.070582,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5896031469",
    "name": "Pyeongtaek",
    "nameKo": "평택",
    "lat": 36.9899168,
    "lng": 127.0863693,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5895868462",
    "name": "Seonghwan",
    "nameKo": "성환",
    "lat": 36.9153776,
    "lng": 127.1270569,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5895878220",
    "name": "Jiksan",
    "nameKo": "직산",
    "lat": 36.8701914,
    "lng": 127.1443262,
    "lines": [
      "1"
    ]
  },
  {
    "id": "4718341773",
    "name": "Dujeong",
    "nameKo": "두정",
    "lat": 36.8332818,
    "lng": 127.149214,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5894856838",
    "name": "Cheonan",
    "nameKo": "천안",
    "lat": 36.8106632,
    "lng": 127.1466993,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5894856981",
    "name": "Bongmyeong",
    "nameKo": "봉명",
    "lat": 36.8009468,
    "lng": 127.1352651,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5894856995",
    "name": "Ssangyong",
    "nameKo": "쌍용",
    "lat": 36.7933314,
    "lng": 127.1205757,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5894857008",
    "name": "Asan",
    "nameKo": "아산",
    "lat": 36.7917816,
    "lng": 127.1035459,
    "lines": [
      "1"
    ]
  },
  {
    "id": "9213388326",
    "name": "Tangjeong",
    "nameKo": "탕정",
    "lat": 36.7878853,
    "lng": 127.0835332,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5894627116",
    "name": "Baebang",
    "nameKo": "배방",
    "lat": 36.7771457,
    "lng": 127.0519158,
    "lines": [
      "1"
    ]
  },
  {
    "id": "8890027524",
    "name": "Onyangoncheon",
    "nameKo": "온양온천",
    "lat": 36.7806844,
    "lng": 127.002185,
    "lines": [
      "1"
    ]
  },
  {
    "id": "8874550904",
    "name": "Sinchang",
    "nameKo": "신창",
    "lat": 36.7694233,
    "lng": 126.9507896,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5904958056",
    "name": "Seodongtan",
    "nameKo": "서동탄",
    "lat": 37.1956686,
    "lng": 127.0518219,
    "lines": [
      "1"
    ]
  },
  {
    "id": "5340688293",
    "name": "Gochon",
    "nameKo": "고촌",
    "lat": 37.6013319,
    "lng": 126.7701876,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "4636808676",
    "name": "Pungmu",
    "nameKo": "풍무",
    "lat": 37.6124305,
    "lng": 126.7324458,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5340642603",
    "name": "Sau",
    "nameKo": "사우",
    "lat": 37.6203085,
    "lng": 126.7196924,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5340642724",
    "name": "Geolpo Bukbyeon",
    "nameKo": "걸포북변",
    "lat": 37.6315929,
    "lng": 126.7058836,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5340662955",
    "name": "Unyang",
    "nameKo": "운양",
    "lat": 37.6538351,
    "lng": 126.683853,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5340662972",
    "name": "Janggi",
    "nameKo": "장기",
    "lat": 37.6440357,
    "lng": 126.6689623,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5340663023",
    "name": "Masan",
    "nameKo": "마산",
    "lat": 37.640616,
    "lng": 126.6441105,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "10814394643",
    "name": "Gurae",
    "nameKo": "구래",
    "lat": 37.6454185,
    "lng": 126.6287137,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "5340678916",
    "name": "Yangchon",
    "nameKo": "양촌",
    "lat": 37.6416447,
    "lng": 126.6147532,
    "lines": [
      "airport"
    ]
  },
  {
    "id": "6046634697",
    "name": "수락산",
    "nameKo": "수락산",
    "lat": 37.6770108,
    "lng": 127.0552337,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6046634703",
    "name": "마들",
    "nameKo": "마들",
    "lat": 37.6647424,
    "lng": 127.0577568,
    "lines": [
      "7"
    ]
  },
  {
    "id": "2111825348",
    "name": "중계",
    "nameKo": "중계",
    "lat": 37.6455228,
    "lng": 127.0638548,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6046634707",
    "name": "하계",
    "nameKo": "하계",
    "lat": 37.6359753,
    "lng": 127.0682067,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6046634708",
    "name": "공릉",
    "nameKo": "공릉",
    "lat": 37.6256062,
    "lng": 127.0729869,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6046634710",
    "name": "먹골",
    "nameKo": "먹골",
    "lat": 37.6114362,
    "lng": 127.0775866,
    "lines": [
      "7"
    ]
  },
  {
    "id": "4706526694",
    "name": "중화",
    "nameKo": "중화",
    "lat": 37.6016296,
    "lng": 127.07945,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6046634712",
    "name": "면목",
    "nameKo": "면목",
    "lat": 37.5883794,
    "lng": 127.0875458,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6046634739",
    "name": "사가정",
    "nameKo": "사가정",
    "lat": 37.5807153,
    "lng": 127.0883912,
    "lines": [
      "7"
    ]
  },
  {
    "id": "3823777524",
    "name": "용마산",
    "nameKo": "용마산",
    "lat": 37.5738974,
    "lng": 127.0864879,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6046634750",
    "name": "중곡",
    "nameKo": "중곡",
    "lat": 37.5662958,
    "lng": 127.08449,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6046633859",
    "name": "어린이대공원",
    "nameKo": "어린이대공원",
    "lat": 37.5476281,
    "lng": 127.0743859,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955208",
    "name": "Jayang",
    "nameKo": "자양",
    "lat": 37.5308705,
    "lng": 127.0664071,
    "lines": [
      "7"
    ]
  },
  {
    "id": "2111924741",
    "name": "청담",
    "nameKo": "청담",
    "lat": 37.5188573,
    "lng": 127.0500373,
    "lines": [
      "7"
    ]
  },
  {
    "id": "436832405",
    "name": "학동",
    "nameKo": "학동",
    "lat": 37.5139701,
    "lng": 127.0307332,
    "lines": [
      "7"
    ]
  },
  {
    "id": "2279487866",
    "name": "반포",
    "nameKo": "반포",
    "lat": 37.5081855,
    "lng": 127.011619,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955191",
    "name": "Naebang",
    "nameKo": "내방",
    "lat": 37.4872377,
    "lng": 126.9921169,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955183",
    "name": "Isu",
    "nameKo": "이수",
    "lat": 37.4853378,
    "lng": 126.9819566,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955158",
    "name": "남성",
    "nameKo": "남성",
    "lat": 37.4843794,
    "lng": 126.9718787,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955148",
    "name": "숭실대입구",
    "nameKo": "숭실대입구",
    "lat": 37.4956558,
    "lng": 126.9541388,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955147",
    "name": "상도",
    "nameKo": "상도",
    "lat": 37.5032145,
    "lng": 126.9476896,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955124",
    "name": "장승배기",
    "nameKo": "장승배기",
    "lat": 37.5049927,
    "lng": 126.9391954,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955112",
    "name": "신대방삼거리",
    "nameKo": "신대방삼거리",
    "lat": 37.49972,
    "lng": 126.9282087,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955111",
    "name": "보라매",
    "nameKo": "보라매",
    "lat": 37.4999833,
    "lng": 126.919781,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955110",
    "name": "신풍",
    "nameKo": "신풍",
    "lat": 37.5001548,
    "lng": 126.9089367,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048953571",
    "name": "남구로",
    "nameKo": "남구로",
    "lat": 37.485404,
    "lng": 126.8866733,
    "lines": [
      "7"
    ]
  },
  {
    "id": "8761155422",
    "name": "Cheolsan",
    "nameKo": "철산",
    "lat": 37.4760589,
    "lng": 126.8677626,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6048955086",
    "name": "광명사거리",
    "nameKo": "광명사거리",
    "lat": 37.479621,
    "lng": 126.8538115,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6050655875",
    "name": "천왕",
    "nameKo": "천왕",
    "lat": 37.4863535,
    "lng": 126.8389512,
    "lines": [
      "7"
    ]
  },
  {
    "id": "2111940162",
    "name": "Jangam",
    "nameKo": "장암",
    "lat": 37.7001801,
    "lng": 127.053075,
    "lines": [
      "7"
    ]
  },
  {
    "id": "7185807400",
    "name": "Sinnae",
    "nameKo": "신내",
    "lat": 37.6124026,
    "lng": 127.1046462,
    "lines": [
      "6"
    ]
  },
  {
    "id": "7864301049",
    "name": "Omokcheon",
    "nameKo": "오목천",
    "lat": 37.2429062,
    "lng": 126.963125,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7872218776",
    "name": "Eocheon",
    "nameKo": "어천",
    "lat": 37.2503749,
    "lng": 126.9081819,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7863473544",
    "name": "Yamok",
    "nameKo": "야목",
    "lat": 37.2616308,
    "lng": 126.8833633,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "7872218729",
    "name": "Sari",
    "nameKo": "사리",
    "lat": 37.2915384,
    "lng": 126.8573725,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5907965096",
    "name": "달월",
    "nameKo": "달월",
    "lat": 37.3807129,
    "lng": 126.7458836,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5907965080",
    "name": "Wolgot",
    "nameKo": "월곶",
    "lat": 37.3921604,
    "lng": 126.7423159,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5907965062",
    "name": "Soraepogu",
    "nameKo": "소래포구",
    "lat": 37.4013038,
    "lng": 126.7325487,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5907965001",
    "name": "인천논현",
    "nameKo": "인천논현",
    "lat": 37.4004832,
    "lng": 126.7215322,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5907964982",
    "name": "Hogupo",
    "nameKo": "호구포",
    "lat": 37.4020968,
    "lng": 126.7077547,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5907964905",
    "name": "Namdong Induspark",
    "nameKo": "남동인더스파크",
    "lat": 37.4082483,
    "lng": 126.6943986,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5910775695",
    "name": "Woninjae",
    "nameKo": "원인재",
    "lat": 37.4136809,
    "lng": 126.6856687,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5910775684",
    "name": "Yeonsu",
    "nameKo": "연수",
    "lat": 37.4183698,
    "lng": 126.6779472,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5910775256",
    "name": "Songdo",
    "nameKo": "송도",
    "lat": 37.4303043,
    "lng": 126.6538721,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5910775615",
    "name": "Inha University",
    "nameKo": "인하대",
    "lat": 37.4489904,
    "lng": 126.6493767,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5910775262",
    "name": "Sungui",
    "nameKo": "숭의",
    "lat": 37.461239,
    "lng": 126.6370849,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "5910775260",
    "name": "Sinpo",
    "nameKo": "신포",
    "lat": 37.4689305,
    "lng": 126.6236807,
    "lines": [
      "bundang"
    ]
  },
  {
    "id": "8566458091",
    "name": "Hanam Geomdansan",
    "nameKo": "하남검단산",
    "lat": 37.5397123,
    "lng": 127.2237049,
    "lines": [
      "5"
    ]
  },
  {
    "id": "8566458089",
    "name": "Hanam City Hall (Deokpung·Sinjang)",
    "nameKo": "하남시청",
    "lat": 37.5416948,
    "lng": 127.2070277,
    "lines": [
      "5"
    ]
  },
  {
    "id": "7798230510",
    "name": "하남풍산",
    "nameKo": "하남풍산",
    "lat": 37.5528048,
    "lng": 127.2043263,
    "lines": [
      "5"
    ]
  },
  {
    "id": "5448542683",
    "name": "Misa",
    "nameKo": "미사",
    "lat": 37.5630584,
    "lng": 127.1927747,
    "lines": [
      "5"
    ]
  },
  {
    "id": "8566458081",
    "name": "Gangil",
    "nameKo": "강일",
    "lat": 37.5575854,
    "lng": 127.1760948,
    "lines": [
      "5"
    ]
  },
  {
    "id": "6050655863",
    "name": "까치울",
    "nameKo": "까치울",
    "lat": 37.5062561,
    "lng": 126.8113774,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6050655851",
    "name": "부천종합운동장",
    "nameKo": "부천종합운동장",
    "lat": 37.5054654,
    "lng": 126.7972534,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6050655850",
    "name": "춘의",
    "nameKo": "춘의",
    "lat": 37.5037437,
    "lng": 126.7871771,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6050655845",
    "name": "신중동",
    "nameKo": "신중동",
    "lat": 37.5030595,
    "lng": 126.7762185,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6050654945",
    "name": "부천시청",
    "nameKo": "부천시청",
    "lat": 37.5047828,
    "lng": 126.7631827,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6050654943",
    "name": "상동",
    "nameKo": "상동",
    "lat": 37.5058462,
    "lng": 126.7531662,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6050654948",
    "name": "삼산체육관",
    "nameKo": "삼산체육관",
    "lat": 37.5065175,
    "lng": 126.7423065,
    "lines": [
      "7"
    ]
  },
  {
    "id": "2360117049",
    "name": "굴포천",
    "nameKo": "굴포천",
    "lat": 37.5070361,
    "lng": 126.7313177,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6050655840",
    "name": "Bupyeong-gu Office",
    "nameKo": "부평구청",
    "lat": 37.5075712,
    "lng": 126.7198593,
    "lines": [
      "7"
    ]
  },
  {
    "id": "6185441878",
    "name": "Sangok",
    "nameKo": "산곡",
    "lat": 37.5086158,
    "lng": 126.7036796,
    "lines": [
      "7"
    ]
  },
  {
    "id": "8754538368",
    "name": "Seongnam",
    "nameKo": "석남",
    "lat": 37.5063954,
    "lng": 126.6731764,
    "lines": [
      "7"
    ]
  },
  {
    "id": "9589229143",
    "name": "Byeollaebyeolgaram",
    "nameKo": "별내별가람",
    "lat": 37.6680941,
    "lng": 127.1169523,
    "lines": [
      "4"
    ]
  },
  {
    "id": "9589229145",
    "name": "Onam",
    "nameKo": "오남",
    "lat": 37.7057341,
    "lng": 127.1923455,
    "lines": [
      "4"
    ]
  },
  {
    "id": "9589229146",
    "name": "Jinjeop",
    "nameKo": "진접",
    "lat": 37.7212032,
    "lng": 127.2031634,
    "lines": [
      "4"
    ]
  },
  {
    "id": "10989473140",
    "name": "Yeoncheon",
    "nameKo": "연천",
    "lat": 38.1004613,
    "lng": 127.0738629,
    "lines": [
      "1"
    ]
  },
  {
    "id": "11433141474",
    "name": "Jeongok",
    "nameKo": "전곡",
    "lat": 38.0237849,
    "lng": 127.0724112,
    "lines": [
      "1"
    ]
  },
  {
    "id": "11433141476",
    "name": "Cheongsan",
    "nameKo": "청산",
    "lat": 37.9943328,
    "lng": 127.0736759,
    "lines": [
      "1"
    ]
  },
  {
    "id": "12455789582",
    "name": "Kintex",
    "nameKo": "킨텍스",
    "lat": 37.6651542,
    "lng": 126.748263,
    "lines": [
      "gyeongui"
    ]
  },
  {
    "id": "12455789584",
    "name": "Unjeongjungang",
    "nameKo": "운정중앙",
    "lat": 37.7161256,
    "lng": 126.7281994,
    "lines": [
      "gyeongui"
    ]
  }
] as Station[];
